### ISSUE TITLE
Workspace Landing Page

### ISSUE THREAD

**Issue by ryngonzalez** [airbnb/Lona#11]
## Context

> Add landing page that allows workspace selection and shows the contents of the workspace

To work in Lona Studio, you'll need a properly configured workspace. A workspace is a directory containing, optionally, the following files:

![workspace](https://user-images.githubusercontent.com/635300/33226758-ab24bdb4-d149-11e7-8011-3b56b4948804.png)

### `colors.json`
<img width="1552" alt="screenshot 2017-11-24 18 42 45" src="https://user-images.githubusercontent.com/635300/33226628-48c1fda0-d147-11e7-8f54-7ec75ba681f8.png">

### `textStyles.json`
<img width="1552" alt="screenshot 2017-11-24 18 42 01" src="https://user-images.githubusercontent.com/635300/33226624-3422816c-d147-11e7-94be-dd1d04560a10.png">

- `gradients.json`
- `shadows.json`
- `types.json`

These files contain shared definitions of aspects of the design system that you're working in—they define the values that are available when creating or editing components in the workspace.

If you're working on multiple design systems, you may need to jump between different workspaces:

![workspaces](https://user-images.githubusercontent.com/635300/33226765-c60590d6-d149-11e7-8f21-9f3d27aadd56.png)

## Goals

We need a way of 

1. Creating an initial workspace to work out of as a first time user, with some default values for the typography and color definitions
2. Choosing what workspace to work out of for my current session
3. Seeing an overview of what's in a workspace (components, shared styles, etc.)
4. Changing my current workspace to something else

## Proposal
* Design a landing page that immediately shows up when starting Lona Studio. 
* It allows you to pick from recently used workspaces, or to create a new workspace with some initial defaults. 
* The listing of the workspace gives some indication of what's in the workspace (components, shared styles, etc.)

Wireframe of idea is here in [this Figma document](https://www.figma.com/file/VfalXJegltN9dabJxjxTzfvb/Workspace-Landing-Page?node-id=1%3A3): 

![wireframe](https://user-images.githubusercontent.com/635300/33227178-33db8d06-d152-11e7-9f8f-7e2656b9e3b4.png)

## Questions
While the proposal addresses creating an initial workspace, choosing a workspace for a current session, and switching workspaces, it doesn't do a sufficient job giving you a good overview of your workspace—to do this well, I think we'll need to do more work in the interface once a workspace has been selected to indicate more about the components, type styles, colors that are a part of the system.

## Working Document
To be transparent and allow collaboration on the design, the work is being done in [this linked Figma document](https://www.figma.com/file/VfalXJegltN9dabJxjxTzfvb/Workspace-Landing-Page) that should be open to the public. The first page (see list in top left) will have the final design, the second page has the wireframe from this issue, and the third has some pictures of inspiration.

**Comment by dabbott** [comment]
@ryngonzalez this is a fantastic overview! It's really easy to jump in at the right point for discussion.

I think the goals are mostly right, but I would say workspaces in Lona are a slightly different use case than e.g. Framer projects. Framer projects are more analogous to Lona components than to Lona workspaces I think. In Framer it's likely I'll be juggling several different projects at any time, for different screens/features. Similarly, in Lona I'll be juggling several different components at a time. However, in Lona I'll _most likely_ have one primary design system that I work with for the duration of a project. 

I may need to switch workspaces from time to time, but it's not as common as switching between components. Because of this, I think we should deprioritize goal (2). I think instead we should prioritize jumping into prior _components_ in a workspace, since it's more likely I'm trying to pick up work on an existing component than hop into another workspace. 

I have a few other tweaks too. Here's how I'd update the goals:

1. Creating **or importing** an initial workspace to work out of as a first time user, with some default values for the typography and color definitions
2. Seeing an overview of what's in a workspace (components, shared styles, etc.)
> This is so I know I'm in the right workspace if I want to make modifications or create a new component. Right now there's no indicator of which workspace I'm in when I launch Lona Studio, and I've often started a new component and not realized I'm in the wrong workspace until I try to pick a color).
3. **Choosing what component to work on for my current session: finding an existing component or creating a new one**
4. Changing my current workspace to something else

With that in mind, I'd probably have the UI _assume_ the current workspace, but allow switching if needed.

Since goal (1) is a less common occurrence, I could imagine having a fairly distinct UI for the empty state. 

Also, I think importing may be just as common, or more common, than creating a workspace. When I try to onboard people at Airbnb, I currently send them a zip of the workspace, but I'd like to send them a URL to a github repo. When launching Lona studio in the blank state, or when creating a new workspace, it could be something like: "Create a new workspace", or "Import an existing workspace", where import has a box to paste in a URL or something. Importing a sharable git URL is nice since we'll want to keep things version controlled and offer tools for merging eventually.

**Comment by ljharb** [comment]
It might also be nice to use a GitHub repo url and keep the workspace synced - ie, integrate git into Lona.

**Comment by dabbott** [comment]
@ljharb yes, totally!

**Comment by dabbott** [comment]
Carrying a few things over from https://github.com/airbnb/Lona/issues/11:

When creating a new component, it would be useful to be able to choose a starting "template", e.g. I want to make a "component" or a "screen". This will help us configure the new file automatically, rather than having to manually tweak the canvases.

We also brainstormed a few ideas for what this could look like.

There is probably a "workspace screen". Perhaps this is/isn't a separate launch screen modal. Perhaps there are indicators about which workspace your component is in. Perhaps we show the various new "templates" and existing components in the workspace screen.

![](https://user-images.githubusercontent.com/1274858/33766746-2b47896a-dc1f-11e7-8373-6fd59e6293e1.png)

Another source of inspiration is the new Photoshop CC 2017 launch experience:

![screen_shot_2017-12-08_at_12_02_53_pm](https://user-images.githubusercontent.com/1198882/33796648-d0ca7fd0-dcad-11e7-81cf-d5544db158e0.png)

![screen_shot_2017-12-08_at_12_02_47_pm](https://user-images.githubusercontent.com/1198882/33796690-93096606-dcae-11e7-9e51-de031b9b5b2f.png)

I think the photoshop launch screens seem a little closer to our use case than the Framer/Sketch launch screens.

**Comment by dennislaupman** [comment]
Another screen for Inspiration: 

Lingo component manager

![screen shot 2017-12-13 at 11 44 15](https://user-images.githubusercontent.com/1274858/33934387-0bd4e662-dff9-11e7-8302-ee8424c48c8b.png)


![screen shot 2017-12-13 at 11 40 36](https://user-images.githubusercontent.com/1274858/33934274-b7cc7b7a-dff8-11e7-9eae-3ad33d9f406d.png)

**Comment by dabbott** [comment]
I think this is in a decent state and we can revisit if needed in the future.

**Comment by ryngonzalez** [comment]
👍
