### ISSUE TITLE
Text align ignored from textStyles.json

### ISSUE THREAD

**Issue by haswalt** [airbnb/Lona#16]
Trying out typography with textAlign: center and it isn't reflected on the canvas.

**Comment by dabbott** [comment]
Thanks for looking into this. 

Do you think `textAlign` should be an attribute of text styles, or a parameter of the `Text` component?

At least at Airbnb, text alignment isn't part of the typography guidelines. It'd be part of the individual component that needs aligned text. Basically I've been imagining it going here somewhere:

![screen_shot_2017-11-25_at_9_33_44_am](https://user-images.githubusercontent.com/1198882/33233140-76519a30-d1c6-11e7-941c-b5f2d4f1b3d4.png)

However, Sketch includes alignment as part of the text style, so that could make sense too. Or potentially it can be part of the text style, but also overriden by the Text component.

cc @ryngonzalez

**Comment by haswalt** [comment]
I agree that it really should be part of the component, however I also envisioned people using the studio outside of a pure component system, say just for generating sketch files from unified DLS.

Having it on the text style is convenient but actually causes more issues I think as you'd probably end up overriding it more often than not in the course of designing full featured projects.

Probably makes more sense to leave it solely up to the component how the text should be aligned, also considering that by default the text component is set to fit content which means textAlign: center isn't immediately effective.

**Comment by ryngonzalez** [comment]
> Having it on the text style is convenient but actually causes more issues I think as you'd probably end up overriding it more often than not in the course of designing full featured projects.

I agree with the sentiment here; I think alignment is going to generally be use-specific, so it would make more sense to keep it out of the text styles. If alignment needs to be reused and shared, it can be encoded into a component, with a use case (and appropriate name) in mind.

**Comment by ryngonzalez** [comment]
Closing this for now! Please reopen if needed.
