### ISSUE TITLE
Add shadow support

### ISSUE THREAD

**Issue by NghiaTranUIT** [airbnb/Lona#29]
## Motivation
The shadow is the must-have feature in all of design tools, such as Sketch, Photoshop, etc.
So, there is no reason Lona doesn't support it. Let do it 😉

## Design
Inspired how Sketch does.
<img width="214" alt="screen shot 2017-12-05 at 10 07 21 pm" src="https://user-images.githubusercontent.com/5878421/33614122-07bc7d6a-da09-11e7-8287-88844015547e.png">

## Acceptance Criteria
+ Able to add/delete one or more shadow layers
+ Support Color, Blur, X, Y, Spread parameters.
+ Allow to save/load Shadow configuration to TextStyles
+ Reflex intermediately when adjusting the parameters
+ Acceptable performance.

## TextStyle.json
I suggest the Shadow format in TextStyle.json
```
{
    "id": "display4",
    "name": "Display 4",
    "fontFamily": "Roboto",
    "fontWeight": "300",
    "fontSize": 112,
    "lineHeight": 120,
    "color": "black",
    "shadow": {
      "color": "black"
      "x": 0,
      "y": 1,
      "blur": 1,
      "spread": 1
    }
},
```
## Implementation 
NSShadow is potential candidate for rendering Shadow and fully support with NSAttributeText as well.
For clearly, NSShadow take configuration from TextStyle with correspond parameter then initializing appropriately.

## Performance 
In order to improve the performance when drawing the shadow, I suggest we `rasterize` the layer and `rasterizationScale`, which match with the screen scale.

---
@dabbott Looking forward to hearing your thought 🔥
If it's good, I'm happy for contributing ⭐️

**Comment by bielikb** [comment]
im happy to help too ;)

**Comment by dabbott** [comment]
Totally agree, Lona needs shadows! Thank you for the detailed writeup 😄 

I have code for reading in shadow configurations on the `shadows` branch: https://github.com/airbnb/Lona/compare/shadows?expand=1

I think shadows should be configured per workspace with `shadows.json` just like colors, text styles, and gradients. This will allow us to refer to shadows by `id` from within `textStyles.json`.

The shadow config would look like:

```json
{
  "shadows": [
    {
      "id": "elevation1",
      "name": "Elevation 1",
      "color": "black",
      "x": 0,
      "y": 2,
      "blur": 4
    }
  ]
}
```

For example:

```json
{
    "id": "display4",
    "name": "Display 4",
    "fontFamily": "Roboto",
    "fontWeight": "300",
    "fontSize": 112,
    "lineHeight": 120,
    "color": "black",
    "shadow": "elevation1"
}
```

I think we could probably _start_ by supporting a single shadow, and then add the ability to add multiple shadows from there (e.g. turn it into an array).

I think we can also start with just `blur` (no `radius`), since shadows on iOS (as far as I know) come with built in support for blur but not radius. We can figure out how to add `radius` later.

### Code generation (is it possible?)

|Platform|Feasibility|Implementation|
|---|---|---|
|iOS|✅ |Easy, we just use CALayer shadow|
|Web|✅ |Easy, with boxShadow/textShadow|
|Android|⚠️ |Harder, we'll likely need to generate a 9-patch for custom shadows... but that's OK I think. better than not supporting custom shadows|

### Shadow picking UI

Probably something like the color picking UI to start with. Imagine this, but with shadows instead:

![screen shot 2017-12-06 at 11 26 58 am](https://user-images.githubusercontent.com/1198882/33681101-6c99fe8c-da78-11e7-82c3-3cf12a985065.png)

I'm actually not sure what the best implementation would be in Lona Studio... what you're describing with `NSShadow` and `NSAttributedString` sounds reasonable. Do you want to try an implementation @NghiaTranUIT? If so, you should probably work off my `shadows` branch.

**Comment by NghiaTranUIT** [comment]
I didn't awake we should separate `shadow.json` as individual component like `color.json` and `textStyles.json` does. Thanks for useful advice. 
In addition, it obviously to reuse the Color Picker.
I will give a try on shadow, because it seems to not difficult to me than other tasks 🤣

**Comment by NghiaTranUIT** [comment]
I have a question.
If we only have the Shadow Picker to pick it from `shadow.json`, where I can create new Shadow like Sketch does ?

**Comment by bielikb** [comment]
Im comming from iOS background -> so setting shadow on CALayer's on iOS makes sense. Performance wise it can be quite slow in table views, collection views, but I guess that's up to developer to decide how he will handle optimizations in his project. 
In my projects I'm using small extension for setting shadow, that defines to which side the shadow should be set (e.g. top, bottom, etc). I think your shadow picker could visualize this simple "alignment" cases.

If you guys need some help with implementation, e.g. to parse the shadow json into it's respective model, etc, just let me know. Im happy to help.

**Comment by dabbott** [comment]
@NghiaTranUIT yes, I think creating shadows like in Sketch is another separate task/feature. Let's start with trying to render shadows on the canvas from `shadows.json`, and after that we'll figure out how to edit them.

Lona should _definitely_ support creating/editing custom colors/text styles/shadows/gradients. Related: https://github.com/airbnb/Lona/issues/14

**Comment by dabbott** [comment]
@bielikb I think if we're gonna get to a Sketch-style shadow editor, there are a couple intermediate steps that you could help with. Since I already have the shadow parsing on my branch... one thing you could help with is the color picker:

![pasted_image_12_7_17__11_16_am](https://user-images.githubusercontent.com/1198882/33733937-2b9fc2ae-db40-11e7-9df3-ac77068adfc0.png)

Unlike most other places where we can pick colors in Lona, for shadows we probably don't want to show the `colors.json` colors (no need to have 12 slight variations of transparent black in the design system). Could you add a custom color picker? If so, I'll make an issue for it and add some detail.

Also, I'd be curious to see your shadow extension. I'm not really an iOS dev, so I don't know the best way to actually generate code for shadows. (Admittedly, I'll probably start by doing whatever we do in the Airbnb app)

**Comment by haswalt** [comment]
for my 2 cents, shadows in react native for example are an odd beast from what I know.

They don't perform as well across different platforms and often it's significantly more performant to add shadows in the form of PNGs instead of generated shadows. CALayer shadows are much more performant than shadows in android land from what i've read.

**Comment by dabbott** [comment]
@haswalt very good point. I forgot to think about React Native 😭 . I will update my post above.

**Comment by dabbott** [comment]
Mostly done!
