### ISSUE TITLE
Generic Picker

### ISSUE THREAD

**Issue by NghiaTranUIT** [airbnb/Lona#44]
## Suggesting a New Feature

We're using Picker for various features, such as ColorPicker, TextStylePicker, ShadowPicker and BackgroundColor, and our app are going to expand bigger in the future. I suppose there are many place we will use picker.
So let make the generic picker and reusing it easily.

## Summary of Idea

+ Design the generic Picker serves many purpose
+ Able to reuse every where in the codebase
+ No boilerplate code 
+ Support Search
+ Customize rowView, paddings and margins.

## Initial Design
Same Color Picker design with Search bar and NSTableView nested.
<img width="219" alt="screen shot 2017-12-12 at 10 12 45 pm" src="https://user-images.githubusercontent.com/5878421/33891794-9a944430-df89-11e7-84a1-fa71df81694e.png">

## Proposed Implementation
Inspired from UITableViewDataSource and UITableViewDelegate.

```swift
protocol GeneralPickerViewDataSource: class {
    func pickerViewDataSource() -> [Any]
    func picker(_ tableView: NSTableView, viewFor item: Any) -> NSView?
    ...
}
```
=> We provide the data source and how to initialize the desired rows

```swift
protocol GeneralPickerViewDelegate {
    func picker(_ picker: GeneralPickerView, didSelectItem item: Any)
    func picker(_ picker: GeneralPickerView, heightOfRow row: Int) -> CGFloat
    ...
}
```
=> We offer delegate for selecting cell or custom height, padding, ... for specific rows

```swift
class GeneralPickerView: NSView {
    weak var dataSource: GeneralPickerViewDataSource?

    // Detail Implementation goes here
    func popover() -> NSPopover {}
}
```

## How to use

```swift
    func showPopover() {
        
        // Create
        let picker = GeneralPickerView(frame: NSRect.zero)
        picker.dataSource = self
        
        // Show
        let popover = picker.popover()
        popover.show(relativeTo: NSRect.zero, of: self, preferredEdge: .maxY)
    }
```
=> Just create picker and show the popover

```swift
extension TextStylePickerButton: GeneralPickerViewDataSource{
    
    func pickerViewDataSource() -> [Any] {
        return CSTypography.styles
    }
    
    func picker(_ tableView: NSTableView, viewFor item: Any) -> NSView? {
        let item = item as! CSTextStyle
        let swatch = TextStyleRow(textStyle: item)
        return swatch
    }
    
    func heightForRow(at row: Int) -> CGFloat {
        return 44.0
    }
}
```
=> The datasource of picker goes here.

Looking forward to hearing your thought 👍

**Comment by dabbott** [comment]
I was focused on internal stuff today... I will leave feedback tomorrow!

**Comment by dabbott** [comment]
Ok, overall this looks really good. There are a few things I'd like to change a little:

---

1. I would prefer to provide configuration parameters to the `GeneralPickerView` through the `init` rather than using the delegate/data source patterns. I find the code becomes much easier to follow when all configuration is declared one place. I know this _goes against Apple/Cocoa patterns_ a bit, but I think it's important as more people start contributing to keep things easy to follow.

For a component with just a few configuration parameters, this is pretty straightforward. We can just use `init` parameters, e.g. https://github.com/airbnb/Lona/blob/7bdc403daba78d2e4ad3278ebc9bb6d4f5115228/LonaStudio/Controls/TextStylePickerView.swift#L113

For components that will likely need _a lot_ of options, I've started using this pattern of calling `init` with a list of options: 
https://github.com/airbnb/Lona/blob/7bdc403daba78d2e4ad3278ebc9bb6d4f5115228/LonaStudio/Controls/CSSearchField.swift#L68
https://github.com/airbnb/Lona/blob/7bdc403daba78d2e4ad3278ebc9bb6d4f5115228/LonaStudio/Controls/CSSearchField.swift#L15-L19
https://github.com/airbnb/Lona/blob/7bdc403daba78d2e4ad3278ebc9bb6d4f5115228/LonaStudio/Controls/TextStylePickerView.swift#L32-L64
There's definitely a lot of boilerplate with this approach, but I think _using_ a component written this way is pretty straightforward. So for components that need a lot of custom configuration, I think this is the best way to go.

In this case, our options would look something like:

```swift
    enum Option {
        case data([Any])
        case viewForItem(NSTableView, Any)
        case didSelectItem((Any) -> Void)
        case heightOfRow((Int) -> CGFloat)
    }
```

If we update the component after instantiation, we would have something like `update(options: [Option])` that reconfigures the component.

It's basically just a matter of how to configure the component: we either extend a class with delegate/dataSource protocol methods, or we call `init` and pass closures. I find the closures more scalable.

--- 

2. Rather than using `Any` as the data type, I'd like to use generics for better type safety.

```swift
class PickerView<Element>: NSView {
      enum Option {
          case data([Element])
          case viewForItem(NSTableView, Element)
          case didSelectItem((Element) -> Void)
          case heightOfRow((Int) -> CGFloat)
      }
}
```

E.g. 
https://github.com/airbnb/Lona/blob/7bdc403daba78d2e4ad3278ebc9bb6d4f5115228/LonaStudio/ListEditors/ListEditor.swift#L289-L300

---

Let me know what you think! I know this is a bit different than how people normally do things, and maybe there's a better way.

**Comment by NghiaTranUIT** [comment]
I agree with your approach since it does against with Coca Pattern a bit, but generally it looks good for starter contributors.

However, I suggest to encapsulate the keyboard and data change logic inside the Picker instead of exposing them.
https://github.com/airbnb/Lona/blob/7bdc403daba78d2e4ad3278ebc9bb6d4f5115228/LonaStudio/Controls/TextStylePickerView.swift#L32-L64

For instance, the initialization of picker looks like:
```swift
 enum Option { 
     //case onChange((String) -> Void)
     //case onKeyPress((KeyCode) -> Void)
     case placeholderText(String)
     case data([Element])
     case viewForItem(NSTableView, Element)
     case didSelectItem((Element) -> Void)
     case heightOfRow((Int) -> CGFloat)
 } 
```
As `onChange` and `onKeyPress` are boilerplate and same logic for any kind of PickerView.

If it's good. I will start implementing now 👍 😄

**Comment by dabbott** [comment]
Ah, that's a great point! Encapsulating onChange and onKeyPress is better.

Yep, looks good to me ✅

**Comment by dabbott** [comment]
Great job @NghiaTranUIT! I'm closing this issue, and we can open a new issue if we find anything to tweak with it.
