### ISSUE TITLE
Add support to web components or polymer 3

### ISSUE THREAD

**Issue by equinusocio** [airbnb/Lona#7]
> Lona Compiler converts .component files to UI code for various targets.
>Support is planned for:
>Web (React)
iOS (Swift)
Android (Kotlin)
React Native
Currently, the only target is React Native, and it's extremely rough (i.e. not really usable).

It could be awesome also support Polymer or native web components to the generated code.

**Comment by ryngonzalez** [comment]
@equinusocio Could you flesh this out a little more? Would be useful to understand your use case!

**Comment by equinusocio** [comment]
Done 👍

**Comment by dabbott** [comment]
I've been thinking about how to handle different targets quite a bit. I think the compiler will have to output some IR which is then consumed by the different code generators. So we would have a code generator that takes in the IR and outputs web components or polymer code.

I think web components and polymer are valuable targets, but I won't be writing/maintaining those code generators since Airbnb wouldn't use them. Probably each code generator should live in a separate repo maintained by the people who use it. I'm gonna close this.
